### ISSUE TITLE
Look into Statistics Plotting & Build Statistics View

### ISSUE THREAD

**Issue by vexance** [Citraro/EmployeeTempTracker#41]

**Comment by ahedgpath** [comment]
So, I'd like to have a formula that averages a persons temp over time, to give us a baseline for that time of day. 
we'd us that against the current measurement and get the MEAN or some other math word that you guys know about to make a decision on their temp.

14.	Is there any additional functionality you would like to see in the web application? Analytics?
a.	Graphing over time would be cool but not needed.
b.	One thing we track is if someone is “missing” from the temp check that day. Basically there is a list of employees and that day’s temp. IF someone doesn’t have a temp, they are either not in that day or didn’t do the temp check.
c.	Any compliance supporting functionality – dates/times are especially important in ensuring compliance and minimizing audit risk
